### PR TITLE
Use attr() to set the sort order value in the HTML

### PR DESCRIPTION
**Pull request by adam-thomas**
@wytrych @KevinEtienne @todd-dembrey review please?

### CODE REVIEW

**Comment by wytrych** [comment]
Nice catch

**Comment by adam-thomas** [comment]
Thanks :) (only took me literally all day... :P)

**Comment by meshy** [comment]
Related to https://github.com/incuna/django-orderable/issues/32?

**Comment by adam-thomas** [comment]
Don't think so, just a small (but significant) JS bug.

**Comment by adam-thomas** [comment]
Monday morning bump!

**Comment by adam-thomas** [comment]
Ta :)

**Pull request merged**
